version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6380:6379" # Changed host port to 6380
    volumes:
      - redis_data:/data

  fastapi:
    build: ./fastapi
    ports:
      - "8080:8000" # Changed host port to 8080
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379 # Port inside the container remains 6379

volumes:
  redis_data:
